let $LANG = 'en'
set nocompatible

filetype plugin indent on
syntax on

filetype on
set showcmd

runtime macros/matchit.vim

set number
set relativenumber
set showmatch
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
set list lcs=trail:·,tab:»»
set foldmethod=syntax
set foldlevelstart=999
set complete+=d

set wildmenu
set wildignore+=*/tmp/*,*.so,*.out,*.exe,*.app,*.dll,*.a,*.la,*.lib,*.swp,*.zip,*.meta
set wildignore+=*.swp,*.bak
set wildignore+=*.o,*.d,*.obj
set wildignore+=*.pyc,*.class,*.sln,*.Master,*.csproj,*.csproj.user,*.cache,*.dll,*.pdb,*.min.*
set wildignore+=*/.git/**/*,*/.hg/**/*,*/.svn/**/*
set wildignore+=*/min/*
set wildignore+=tags,cscope.*
set wildignore+=*.tar.*
set wildignore+=*/bower_components/**
set wildignore+=*/node_modules/**
set wildignore+=*/output/**
set wildignorecase
set wildmode=list:full
set path& | let &path .= "**"

set conceallevel=0

set mouse=
if has("termguicolors") && has("nvim")
  set t_8f=u;%lu;%lum
  set t_8b=u;%lu;%lum
  set termguicolors
endif

set ttyfast
set lazyredraw

set nowrap " spacing
set tw=89
set wm=0
augroup Files
  au!
  au BufEnter *.* setlocal colorcolumn=90
  au BufEnter *.* highlight OverLength ctermbg=darkgrey guibg=#693030
  au BufEnter *.* match OverLength /\%91v.*/
augroup END

set shiftround
set tabstop=2 shiftwidth=2

set eol
set expandtab
set autoindent
set backspace=indent,eol,start
set copyindent
set smarttab

" search
set gdefault
set hlsearch
set incsearch
set ignorecase
set smartcase

set hidden " hidden buffers
set splitright " split to right by default

"
source ~/Workspace/dotfiles/vim/plugins.vim
source ~/Workspace/dotfiles/vim/functions.vim
source ~/Workspace/dotfiles/vim/gitignore.vim
source ~/Workspace/dotfiles/vim/keys.vim
source ~/Workspace/dotfiles/vim/colors.vim
source ~/Workspace/dotfiles/vim/filetypes.vim
source ~/Workspace/dotfiles/vim/complete.vim

source ~/Workspace/dotfiles/vim/csharp.vim
source ~/Workspace/dotfiles/vim/purescript.vim
source ~/Workspace/dotfiles/vim/idris.vim
source ~/Workspace/dotfiles/vim/haskell.vim
source ~/Workspace/dotfiles/vim/writing.vim
source ~/Workspace/dotfiles/vim/visual-at.vim
